
name: Dev Branch Pipeline
on:
  # Triggers the workflow on push request events but for all the branches except the "main" branch
  push:
    branches:
      - '*'
      - '!main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
# github.sha is commit id that triggered the workflow
# head_commit.message - is the commit message
jobs:
  call-workflow:
    #You call a reusable workflow by using the 'uses' keyword
    uses: hpatel3747/github-reusable-actions/.github/workflows/ci-dev-branch.yaml@main
    with:
      componentName: user

    #when calling a workflow 'with:' provides map of inputs that are passed to the called workflow